---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "HhiErRKedHxByjfP9X6vVcHbcV5ZmLRHrU5pF4XGJ7kHEq+/8qe9SXE\
    WXIRSTsb9uEdOe20GgoAXYaIT7SKzX5hLgEqtCMNXUrv3tArAbR6QnDyiYSXQVoM2L\
    bdhb9dypxqNBoq8rELYRT0wzJKALB832eLtGKGSsNT2jKda5OP41zyyZZVzyiB2DWz\
    TOqfatBIZcg1ez/plQT5dIrAi8TdAhiHkz/1VH3Twt4wqwQIGrVlJZBjhiv/1dWn9K\
    EirCPYKUbo4xQ6z+u+SiC+Qp5UpMe8rrd/Rf98cwLVoJpDMzKD3FLwYIp6uZrJnewR\
    zVeVQhBhM1E6OldlrF5+ojfNq7OM68tiGS8AetlTpUaaawgHwNkOR71aTXc/qjVr/R\
    NXYJwfFqf/5tV6CD+ubub9PXek6ZOxNPriBfEnHog7kS8euKzdfnRO9SImSHD4uJa7\
    DXi+1Sf/qeSnFdKRZdt+69+oZkopH0Hy6zN9UyjhHYLHGqgTDJRKIineBuTtRh6RZs\
    Y9872+eoqNFpZaFe6XB20xlryBhk67dOM+rT2cmD6zdvnrYiKZ27f9BDRVyYkFtGeJ\
    HHJ9SkyQMYlQyJOmvmhgzcBf/HeNx5/om+QP1boo7XNR//tvoGvYmHaYUwBHCSZ4AW\
    RDd83jgFdBpCy8WsYR8DThq9FWHIuZWgOM="
    - AWS_DEFAULT_REGION="us-east-2"
    # AWS_SECRET_ACCESS_KEY
    - secure: "LVz8fikxnIWJf8nx7QnLYjXv7JD7I2lAt+7SuQDlajNoAvpJZ716f5m\
    0FNk6jhAgBFQYmMKjsGPHz0AKhCuLPTl70NDId24gE/9dGPHbcsjBZetHcF5LGdMW6\
    z0hGxqKtcCcDwDH7PztflNrTqW4DDY/msjsWlwcRE8p/i1SOErqBFCwCsMMvwl5qeS\
    8uVQ2WsQxUrc7MadO/Yy0kO5sW7vbJBc99ccFf/+S0rpJ/qoXavsnbJl91mS/YpITR\
    Pem/zOE620hmHlhn3U9cXZAeY38A7gfF9itG6rixJX9ju5H8UGk1+HBzVCqh90QFws\
    tO2NZ5Ns6DHfzEFNey7ex97xPj2YkIxzzLwjLuFcTJuNVi97jTpF7wDbKlwmqTJtCb\
    639/pzO45SeCbrboi4+fdUFR1HVSe+i09WbVnjJR3ApUpVJQjrIHkHz8VlJY8IHbtV\
    xvIzalhpN9SubrV+wUuo8Ht8lxBlyoViJPEvwjvbu0oB/uOpLFiZjb2MPfeOq6D1iO\
    wjflHy79kUiKY/1klPybZNOXlY1cyJ1CHysqCP8sqllt08yHvcIkfHarE/ksIXk0lM\
    90vBOYL5LCE2mw0+u4lGR9WZG2WM41/zEfWVbEBi9R58fkR+yGa3gJFL9MI/Z25HG/\
    vLcgp+HW8oWU6ut7dO+aHh0CxLZfMwWgkU="
    # GITHUB_ACCESS_TOKEN
    - secure: "T07BS85f3AuDXwPya5IUy7UViUDHSXh7T8G7iwgTcQ6GZ009Tooy4AV\
    pv/CqiY5w1E/O+gqLy1OHsgwUmrs+z4OItSfBQZy519K6BrOEul34wJKmF/bkuERF9\
    bvimWYZW3M9CabdN6Cg3mlaGhGGmWdLmG/UUbYYYA9jHs5yyfr03muXihniURJ+lRS\
    DutWJowH6A6Jdh2WQyNrnBjooSALMK8rcmjjiIxRjRh1cv6SO2TAKONSTDKm6vMDoN\
    Ng6YtfUgEIr3mRpyCv7XwCJbGd2rsFm+nxmVVZfs2Ta9AILtUyJy1QTh9ozLRf5wmL\
    0nnPoGVZoaKcJ63v74BB0waMq5m+UjAmzrPmRiN9b1jDy7Dry2faczNZYymSNVwLLC\
    bRkC4so4Vo8aVaEA2EEV8xkjXB7DqKeozlI+VEfYYTWPUJz+Bue0nBd/I5W53q/fRA\
    09ZwqRGfXcxoANEGC8bsXjj/W1BS59XiAuRQb92+3fR/ePuNDK0YBPTA9RgvtHzwn5\
    BY4sPnPfMxrEznxArxRYh3OqvlPmsHGaFK2ncEbnIk0Pvz1NJliEcT1LB5x9g3b1eG\
    TLEXwZwwGu9F6P67RA57tzglqkn6bsRfSisXoJ0g5fXVKSaim+mPVt7l/dw0yvn2I0\
    5pLFambdoql3fRGfql21FRuLD9f6p0SJgo="
    - PACKER_BUILD_REGION="us-east-2"
    - PACKER_DEPLOY_REGIONS="us-east-1,us-west-1,us-west-2"
    - PACKER_VERSION="1.4.2"
    - TERRAFORM_VERSION="0.12.3"


# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
    - $HOME/.cache/curl

before_install:
  # make a cache directory for curl downloads
  - mkdir -p $HOME/.cache/curl
  # Install terraform
  - curl --output $HOME/.cache/curl/terraform.zip
      --time-cond $HOME/.cache/curl/terraform.zip --location
      "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
  - sudo unzip -d /opt/terraform $HOME/.cache/curl/terraform.zip
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  # install packer
  - curl --output $HOME/.cache/curl/packer.zip
      --time-cond $HOME/.cache/curl/packer.zip --location
      "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - sudo unzip -o -d /usr/local/bin $HOME/.cache/curl/packer.zip

install:
  - pip install --upgrade --requirement requirements-test.txt
  - export PACKER_IMAGE_VERSION=$(./bump_version.sh show)
  # install roles
  - ansible-galaxy install --force --role-file src/requirements.yml

script:
  - eval $(./update_env.py)
  - pre-commit run --all-files
  - packer validate src/packer.json
  - pytest

deploy:
  # create an image
  - provider: script
    script: ./cisa_wait.sh 30 packer build --timestamp-ui src/packer.json
    on:
      tags: true
