---
dist: xenial
language: python
python: 3.7
# pre-commit hooks can use Docker, so we should go ahead and enable it
services: docker
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "jgVYFUvaYPanAFYWvfdWXo/HzcIqUiDZ8O8K0SNgvCqtEwd+NDmPf97\
    KyVg7xfGVinBVLN2gi0iGvp/SrspKy+2ad3x21JBkdbscWQifLqKm3b4NBp6OWCZQs\
    zPLfLs6smFpyvccd11UfoZ046rinBG9APCJpVFYjwaDqyCu8344y1761g+pHJjP/7u\
    NwX26izLRtaOAXJJ+QydOJ5GpS2jUnDc1p9R04rJmS0UO7SrTeR9lFrkSRg80o80Dt\
    tvuGSyBeUh7K4beLFOP19nL//uprkK611aFpb8zI+FAp0RslL+YBb8+xwb7fInFUoI\
    JFAXFc2ZUrQ8QJ2W8LXCKERRA6DxDwgsTGHzzxyqNF+rrQO2gkZPgUs/+HhU6qYzrh\
    O+UgspQjhexXFGl+7UFTkLgEmVaUqKb28xXb6nC/3Phuelwsu8yBOs9tRH8IjYZC6z\
    kr5Lz8vpv2u7VHU5tn7jYUI5RWrSP/234qaKkmD9gXjw0jequdOmDQT0VcuWDinN5w\
    tFoP4K83hW76AH2kx4ijjlVVh41vXl4WoqdTEZCrh0gTYZmflwK360CCUoTYj4IsVB\
    T6VYn3Yj1lAEkvZfuqwABGkB3GslsyEFJB3q9+yQUUH150wF4rLnw+r8J3QbKJximf\
    GlvjgMzHI9NcCX7JRnPxhkn2QoBuKJCcQY="
    - AWS_DEFAULT_REGION="us-east-2"
    # AWS_SECRET_ACCESS_KEY
    - secure: "T2DoaM0ft65k73Dg9HLOoBH0kCBpR9Uf1I41hIV1DuPD77Bagm3/gnc\
    TeMrZiEGiOqwgZqNPv++vRV0ErImqw6zdAazBODdVJNii6p7D4WhvU8xWepH7J0t7t\
    nyseK+cpAVtWjonvh7HAC4kEOPFTJqeiUjfE5RxEWIg1kLdJhvje017OEZCJ1aGxbI\
    HlPXxGluL/XW8KDbSwxRho1hDs6FPdnS6q/O7gxLaH/RVCc1oeJXFi78pOZikSDGuZ\
    arGZCZyR40eZNTmvwAHPQGb+m0Y1VuiBsVKliwBxa4Q/2N0uX1HBd6smLjF/E+G5o1\
    y79S0V1EOlX5RKNk6SqYf6OMejNjlxLi6X79WXx6U/OQq1eJKzWnhfbmKRgHtbEsoL\
    MY3yQdYSQj19ZoBI9q6+E/ErPaIWhRkB2n26Fb4YfuTGjGyTVwX5DmXVk/LorI3NNa\
    OlTf2Y+PJmxOTO0kQ0Y0koZHJjVW4AnR+zTXvaZ5/wLWUwdBXaJhc95Dkp+tlv0g4R\
    jbpfg/7L4Bl57W1K/dg+yB3qrmTDoxck40ZjeqsUxv7b6DPI4j950PPiA3Lk1FofPO\
    CtBTm/+u12bXEqKzKP+nw1gGL7SmzwLRoRnV06WO6RVW4p7QcKS318DHrYbrwdfHtg\
    ihzpjw+GWxDjcWrwoV2Acj5cTdZrVJ6dsw="
    # GITHUB_ACCESS_TOKEN
    - secure: "CMVLqC2AYZ78mEn8w1GWv3p7Ci5lProngCei/Fzin0KCYrsV+DEBQCm\
    6nKvv/wmEKIy79BpdF2GNwz23uiJXE8VF9A3WBM82coF5KfCO1CporqsQ25cLYSwCF\
    j8AxsT4n5JXHtXVsuNk0QETspZcDBjfOtdIS0p/YYArkpBS69NFJg4d7STcCPnIgRX\
    /06ksN9WRbliiiQ70gdkZpZE5ceqMH3mRiUFFKU9aTF2DnDDaYLVXbHqjtYL621HYa\
    /XywUQ6YZwFEbz8n4XwGqARILJOfz0FPJcKCOAnAnbGwY3ejef15lEMDZQuPzb7kPy\
    hhykpbNKY028781GyQxJrPMYx1AYOlAeP/vkFUGQvMXbOuEF6WLLv3CHsx1MX30EW3\
    bZL5FBgxwvg5v/PgFQNdh8Ma+e02D2p+AHWUCf3VhwHqdKovk3ebDRlF2geJYl8KP7\
    HiqSnKlITsvRxh+tZdvBR7rNv6+PjsjfR00hMI4KY45Z6eoLXcXz9icwT76Q1+Adnz\
    eMACE+Yb3HLdg4mfo6Ni3Fkdz+8ODw750crSsR1/TAGeFL8F+qp+1eqScMbz+vxoyv\
    yKDN3LCV3Sj6nmiE4d3UmjP/YKkQxD9cqCzBFMuUtJKgNajpbuy0WKdtkConb2wxSa\
    3bX4KmUdPpv1mLNg5ugcp+8PWT1/Bb0U2A="
    - PACKER_BUILD_REGION="us-east-2"
    - PACKER_DEPLOY_REGIONS="us-east-1,us-west-1,us-west-2"
    - PACKER_VERSION="1.4.2"
    - TERRAFORM_VERSION="0.12.3"


# Cache pip packages and pre-commit plugins to speed up builds
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
    - $HOME/.cache/curl

before_install:
  # make a cache directory for curl downloads
  - mkdir -p $HOME/.cache/curl
  # Install terraform
  - curl --output $HOME/.cache/curl/terraform.zip
      --time-cond $HOME/.cache/curl/terraform.zip --location
      "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
  - sudo unzip -d /opt/terraform $HOME/.cache/curl/terraform.zip
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  # install packer
  - curl --output $HOME/.cache/curl/packer.zip
      --time-cond $HOME/.cache/curl/packer.zip --location
      "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - sudo unzip -o -d /usr/local/bin $HOME/.cache/curl/packer.zip

install:
  - pip install --upgrade --requirement requirements-test.txt
  - export PACKER_IMAGE_VERSION=$(./bump_version.sh show)
  # install roles
  - ansible-galaxy install --force --role-file src/requirements.yml

script:
  - eval $(./update_env.py)
  - pre-commit run --all-files
  - packer validate src/packer.json
  - pytest

deploy:
  # create an image
  - provider: script
    script: ./cisa_wait.sh 30 packer build --timestamp-ui src/packer.json
    on:
      tags: true
