---
# Both the collections and roles lists must exist in this file because
# we use both ansible-galaxy collection install and ansible-galaxy
# role install to install collections and roles from it.  Note that
# either (or both) can be an empty list, e.g., collections: [].
collections:
  # Required by the following playbooks:
  # - ansible/guacamole.yml (uses amazon.aws.ssm_parameter)
  # - ansible/wazuh_agent.yml (uses amazon.aws.ssm_parameter)
  - amazon.aws
  # Required by the following Ansible roles:
  # - ansible-role-amazon-efs-utils (uses community.general.json_query
  #   and community.general.make)
  # - ansible-role-amazon-ssm-agent (uses community.general.snap)
  # - ansible-role-automated-security-updates (uses community.general.ini_file)
  # - ansible-role-cloudwatch-agent (uses community.general.ini_file)
  # - ansible-role-freeipa-client (uses community.general.ini_file)
  # - ansible-role-httpd (dependency of ansible-role-guacamole that
  #   uses community.general.apache2_module)
  # - ansible-role-persist-journald (uses community.general.ini_file)
  # - ansible-role-systemd-resolved (uses community.general.ini_file)
  - community.general
roles:
  - name: amazon_ssm_agent
    src: https://github.com/cisagov/ansible-role-amazon-ssm-agent
  - name: automated_security_updates
    src: https://github.com/cisagov/ansible-role-automated-security-updates
  - name: banner
    src: https://github.com/cisagov/ansible-role-banner
  - name: chrony_aws
    src: https://github.com/cisagov/ansible-role-chrony-aws
  - name: clamav
    src: https://github.com/cisagov/ansible-role-clamav
  - name: cloudwatch_agent
    src: https://github.com/cisagov/ansible-role-cloudwatch-agent
  - name: devops
    src: https://github.com/cisagov/ansible-role-devops-user
  - name: freeipa_client
    src: https://github.com/cisagov/ansible-role-freeipa-client
  - name: guacamole
    src: https://github.com/cisagov/ansible-role-guacamole
  - name: htop
    src: https://github.com/cisagov/ansible-role-htop
  - name: joiner
    src: https://github.com/cisagov/ansible-role-joiner-user
  - name: nvme
    src: https://github.com/cisagov/ansible-role-nvme
  - name: persist_journald
    src: https://github.com/cisagov/ansible-role-persist-journald
  - name: pip
    src: https://github.com/cisagov/ansible-role-pip
  - name: python
    src: https://github.com/cisagov/ansible-role-python
  - name: remove_python2
    src: https://github.com/cisagov/ansible-role-remove-python2
  - name: systemd_resolved
    src: https://github.com/cisagov/ansible-role-systemd-resolved
  - name: upgrade
    src: https://github.com/cisagov/ansible-role-upgrade
  - name: wazuh_agent
    src: https://github.com/cisagov/ansible-role-wazuh-agent
