---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - banner
    - clamav
    - dev_ssh_access
    - freeipa_client
    - htop
    - joiner
    - persist_journald
