---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  tasks:
    - name: Install and configure automated security updates
      ansible.builtin.include_role:
        name: automated_security_updates
    - name: Install and configure login banner
      ansible.builtin.include_role:
        name: banner
    - name: Install and configure ClamAV
      ansible.builtin.include_role:
        name: clamav
    - name: Create the devops user
      ansible.builtin.include_role:
        name: devops
    - name: Install and configure freeipa client
      ansible.builtin.include_role:
        name: freeipa_client
    - name: Install and configure htop
      ansible.builtin.include_role:
        name: htop
    - name: Create the joiner user
      ansible.builtin.include_role:
        name: joiner
    - name: Configure JournalD to preserve logs across reboots
      ansible.builtin.include_role:
        name: persist_journald
