---
- hosts: all
  name: Install Guacamole Docker composition
  become: yes
  become_method: sudo
  roles:
    - role: guacamole
      vars:
        # The postgres database username and password for guacamole
        postgres_username: >
          {{ lookup('aws_ssm', '/guacamole/postgres_username') }}
        postgres_password: >
          {{ lookup('aws_ssm', '/guacamole/postgres_password') }}
  # boto3 is needed during deployment to fetch SSL certificates.
  # pystache may be used during deployment as part of the process that
  # automatically defines Guacamole connections to other instances
  tasks:
    - name: Install boto3 and pystache
      ansible.builtin.pip:
        executable: pip3
        name:
          - boto3
          - pystache
