---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - dev_ssh_access
    - persist_journald
    - htop
    - clamav

- hosts: aws
  name: AWS-specific roles
  become: yes
  become_method: sudo
  roles:
    - amazon_ssm_agent
    - cloudwatch_agent
    # The instance types used for almost all the instances expose EBS
    # volumes as NVMe block devices, so that's why we need nvme here.
    - nvme

- hosts: all
  name: Install Guacamole Docker composition
  become: yes
  become_method: sudo
  roles:
    - guacamole
  vars:
    # The postgres database username and password for guacamole
    postgres_username: "{{ lookup('aws_ssm', '/guacamole/postgres_username') }}"
    postgres_password: "{{ lookup('aws_ssm', '/guacamole/postgres_password') }}"

# boto3 is needed during deployment to fetch SSL certificates
- hosts: all
  name: Install boto3
  become: yes
  become_method: sudo
  tasks:
    - name: Install boto3
      pip:
        executable: pip3
        name:
          - boto3

# pystache may be used during deployment as part of the process that
# automatically defines Guacamole connections to other instances
- hosts: all
  name: Install pystache
  become: yes
  become_method: sudo
  tasks:
    - name: Install pystache
      pip:
        executable: pip3
        name:
          - pystache
