---
- hosts: all
  name: Setup base image
  become: yes
  become_method: sudo
  roles:
    - upgrade
    - python
    - banner
    - dev_ssh_access
    - persist_journald
    - htop

- hosts: aws
  name: AWS-specific roles
  become: yes
  become_method: sudo
  roles:
    # The instance types used for almost all the instances expose EBS
    # volumes as NVMe block devices, so that's why we need nvme here.
    - nvme

- hosts: all
  name: Install Guacamole Docker composition
  become: yes
  become_method: sudo
  roles:
    - guacamole

- hosts: all
  name: Start up Guacamole Docker composition
  become: yes
  become_method: sudo
  tasks:
    - name: Start up Guacamole Docker composition
      docker_compose:
        project_src: /var/guacamole
