---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import guacamole playbook
  ansible.builtin.import_playbook: guacamole.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml
