---
- name: amazon_ssm_agent
  src: https://github.com/cisagov/ansible-role-amazon-ssm-agent
- name: automated_security_updates
  src: https://github.com/cisagov/ansible-role-automated-security-updates
- name: banner
  src: https://github.com/cisagov/ansible-role-banner
- name: chrony_aws
  src: https://github.com/cisagov/ansible-role-chrony-aws
- name: clamav
  src: https://github.com/cisagov/ansible-role-clamav
- name: cloudwatch_agent
  src: https://github.com/cisagov/ansible-role-cloudwatch-agent
- name: devops
  src: https://github.com/cisagov/ansible-role-devops-user
- name: freeipa_client
  src: https://github.com/cisagov/ansible-role-freeipa-client
- name: guacamole
  src: https://github.com/cisagov/ansible-role-guacamole
- name: htop
  src: https://github.com/cisagov/ansible-role-htop
- name: joiner
  src: https://github.com/cisagov/ansible-role-joiner-user
- name: nvme
  src: https://github.com/cisagov/ansible-role-nvme
- name: persist_journald
  src: https://github.com/cisagov/ansible-role-persist-journald
- name: pip
  src: https://github.com/cisagov/ansible-role-pip
- name: python
  src: https://github.com/cisagov/ansible-role-python
- name: remove_python2
  src: https://github.com/cisagov/ansible-role-remove-python2
- name: upgrade
  src: https://github.com/cisagov/ansible-role-upgrade
