---
- src: https://github.com/cisagov/ansible-role-amazon-ssm-agent
  name: amazon_ssm_agent
- src: https://github.com/cisagov/ansible-role-backports
  name: backports
- src: https://github.com/cisagov/ansible-role-banner
  name: banner
- src: https://github.com/cisagov/ansible-role-chrony-aws
  name: chrony_aws
- src: https://github.com/cisagov/ansible-role-clamav
  name: clamav
- src: https://github.com/cisagov/ansible-role-cloudwatch-agent
  name: cloudwatch_agent
- src: https://github.com/cisagov/ansible-role-dev-ssh-access
  name: dev_ssh_access
- src: https://github.com/cisagov/ansible-role-devops-user
  name: devops
- src: https://github.com/cisagov/ansible-role-freeipa-client
  name: freeipa_client
  version: bugfix/only-use-backports-where-absolutely-necessary
- src: https://github.com/cisagov/ansible-role-guacamole
  name: guacamole
- src: https://github.com/cisagov/ansible-role-htop
  name: htop
- src: https://github.com/cisagov/ansible-role-joiner-user
  name: joiner
- src: https://github.com/cisagov/ansible-role-nvme
  name: nvme
- src: https://github.com/cisagov/ansible-role-persist-journald
  name: persist_journald
- src: https://github.com/cisagov/ansible-role-pip
  name: pip
- src: https://github.com/cisagov/ansible-role-python
  name: python
- src: https://github.com/cisagov/ansible-role-remove-python2
  name: remove_python2
- src: https://github.com/cisagov/ansible-role-upgrade
  name: upgrade
